# Generated by Django 2.2.1 on 2019-07-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='basic_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_project', models.CharField(max_length=10, verbose_name='项目立项年份')),
                ('city', models.CharField(max_length=10, verbose_name='城市')),
                ('land_area', models.FloatField(verbose_name='土地面积(亩)')),
                ('industrial_land_expense', models.FloatField(verbose_name='工业用地费用(万/亩)')),
                ('commercial_land', models.FloatField(verbose_name='商业用地(万/亩)')),
                ('residential_land', models.FloatField(verbose_name='住宅用地(万/亩)')),
            ],
            options={
                'db_table': 'data_analysis_test',
                'ordering': ['year_of_project'],
            },
        ),
    ]
